language: node_js

branches:
  only:
    - master

node_js:
  - 12
  
before_install:
  - (cp .env.example .env)

install:
  - npm install
  
script:
  - npm run lint

after_script:
  - npm run coverage

after_success:
  - codecov --file coverage/lcov.info --disable search